---
- hosts: all
  vars:
    systemd_service_activate: False
    systemd_service_def:
      name: node_exporter
      description: Prometheus node_exporter
      exe: /usr/local/bin/node_exporter
      args: '$NODE_EXPORTER_ARGS'
      env:
        dir: /etc/node_exporter
        filename: env
        data:
          NODE_EXPORTER_ARGS: ''
      start_limit:
        interval: 5
        burst: 10
      restart:
        policy: always
        sec: 120
      after:
        - syslog.target
        - network.target
      wanted_by:
        - multi-user.target
  roles:
  - role: '{{ playbook_dir }}'
