---
- hosts: all
  vars:
    systemd_service_def:
      name: example
      description: example systemd service used to test Ansible role andrewrothstein.systemd_service
#      activate: false
#      enabled: false
      activate: true
      enabled: true
      account:
        create: true
        user: example-user
        group: example-group
      start:
        exe: /bin/bash
        args: -c $BASH_SCRIPT
      user: example_systemd_user
      group: example_systemd_group
      env:
        dir: /etc/example_systemd
        filename: env
        data:
          BASH_SCRIPT: |
            echo hello world
            echo "A: $A"
            echo "B: $B"
          A: foo
          B: gazi
      restart:
        policy: on-failure
      after:
        - syslog.target
        - network.target
      wanted_by:
        - multi-user.target
  roles:
    - role: '{{ playbook_dir }}'
