---
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'

- name: Creating service account
  when:
    - systemd_service_def.account is defined
    - systemd_service_def.account.group is defined
    - systemd_service_def.account.user is defined
  ansible.builtin.include_role:
    name: andrewrothstein.service_account
  vars:
    service_account_def:
      enabled: '{{ systemd_service_def.account.enabled }}'
      user:
        name: '{{ systemd_service_def.account.user }}'
        group: '{{ systemd_service_def.account.group }}'

- name: Configureing systemd service
  when: systemd_service_def is defined
  block:
    - name: Install service definition...
      ansible.builtin.include_tasks: systemd.yml
    - name: Activating/starting {{ systemd_service_def.name }}
      when: systemd_service_def.activate
      become: true
      become_user: root
      ansible.builtin.service:
        name: '{{ systemd_service_def.name }}'
        state: started
        enabled: '{{ systemd_service_def.enabled }}'
