---
- name: creating service account group
  become: yes
  become_user: root
  when: systemd_service_def.group is defined
  group:
    name: '{{ systemd_service_def.group }}'
    state: present

- name: create service account user
  become: yes
  become_user: root
  when: systemd_service_def.user is defined
  user:
    name: '{{ systemd_service_def.user }}'
    group: '{{ systemd_service_def.group }}'
    state: present
