---
- name: Construct systemd env file
  when: systemd_service_def.env is defined
  ansible.builtin.include_tasks: systemd-env.yml
- name: Templating {{ systemd_service_fq_service_unit }}
  become: true
  become_user: root
  ansible.builtin.template:
    src: service.j2
    dest: '{{ systemd_service_fq_service_unit }}'
    mode: '600'
    owner: '{{ systemd_service_def.account.user | default("root") }}'
    group: '{{ systemd_service_def.account.group | default("root") }}'
  notify: Systemd_service_daemon_reload
