---
- name: Mkdir {{ systemd_service_def.env.dir }}
  become: true
  become_user: root
  ansible.builtin.file:
    path: '{{ systemd_service_def.env.dir }}'
    mode: '700'
    state: directory
    owner: '{{ systemd_service_def.account.user | default("root") }}'
    group: '{{ systemd_service_def.account.group | default("root") }}'
- name: Templatizing environment to {{ systemd_service_fq_env_file }}
  become: true
  become_user: root
  ansible.builtin.template:
    src: env.j2
    dest: '{{ systemd_service_fq_env_file }}'
    mode: '600'
    owner: '{{ systemd_service_def.account.user | default("root") }}'
    group: '{{ systemd_service_def.account.group | default("root") }}'
  notify: Systemd_service_restart
