---
- name: mkdir {{ systemd_service_def.env.dir }}
  become: true
  become_user: root
  file:
    path: '{{ systemd_service_def.env.dir }}'
    mode: 0700
    state: directory
    owner: '{{ systemd_service_def.user | default("root") }}'
    group: '{{ systemd_service_def.group | default("root") }}'
- name: templatizing environment to {{ systemd_service_fq_env_file }}
  become: true
  become_user: root
  template:
    src: env.j2
    dest: '{{ systemd_service_fq_env_file }}'
    mode: 0600
    owner: '{{ systemd_service_def.user | default("root") }}'
    group: '{{ systemd_service_def.group | default("root") }}'
  notify: systemd_service_restart
