---
# handlers file for systemd_service
- name: systemd_service_daemon_reload
  become: true
  become_user: root
  when: systemd_service_activate
  systemd:
    daemon_reload: true
- name: systemd_service_restart
  become: true
  become_user: root
  when: systemd_service_activate
  service:
    name: '{{ systemd_service_def.name }}'
    state: restarted
