---
# handlers file for systemd_service
- name: Systemd_service_daemon_reload
  become: true
  become_user: root
  when: systemd_service_def.activate
  ansible.builtin.systemd:
    daemon_reload: true
- name: Systemd_service_restart
  become: true
  become_user: root
  when: systemd_service_def.activate
  ansible.builtin.service:
    name: '{{ systemd_service_def.name }}'
    state: restarted
